---
    name: Errands CI

    on:
        push:
            branches:
                - master
        pull_request:
            branches:
                - master
    jobs:
        test:
            runs-on: ubuntu-latest
            strategy:
                fail-fast: false
                matrix:
                    python-version:
                        - '3.7'
                        - '3.8'
                        - '3.9'
                        - '3.10'
                        - '3.11'
            steps:
                -
                    name: Checkout repository
                    uses: actions/checkout@v2
                -
                    name: Set up Python
                    uses: actions/setup-python@v2
                    with:
                        python-version: ${{ matrix.python-version }}
                -
                    name: Install dependencies
                    run: |
                        python -m pip install --upgrade pip
                        pip install tox
                -
                    name: Run tox tests
                    run: tox -e py${{ matrix.python-version }} -r -c tox.ini
                -
                    name: Archive test artifacts
                    if: always()
                    uses: actions/upload-artifact@v2
                    with:
                        name: ${{ runner.job }}-${{ matrix.python-version }}
                        path: |
                            .coverage/
                            junitxml_report/
    